### ISSUE TITLE
Animal element

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/ExperimentalModelSchema#11]
For the [animalIdentificationMethodList message](https://thejacksonlaboratory.github.io/ExperimentalModelSchema/animal.html), an example is given where a mouse has an ear punch with ID 90. The MGI ID `MGI:1234567` is obviously made up. When I search for it in MGI, I find details about probe [IMAGE clone 1248569](https://www.informatics.jax.org/probe/MGI:662257). If I search for the term "ear punch" then I only find details about the [QTL Erph1](https://www.informatics.jax.org/marker/MGI:3663644). I generally don't think you can find information about individual animals in MGI. I also don't think we should include details such as “ear punch” with a value of 90 in the schema.

The counterpart to the Animal Element in EMS is the [Individual Element in the original GA4GH Phenopackets schema](https://phenopacket-schema.readthedocs.io/en/latest/individual.html#rstindividual). I suggest that we add two additional messages to the individual element:

1. `source`: The purpose of this message is to uniquely assign an EMS packet to a specific data source. It should not be too extensive and should not contain details such as ear punches or cage numbers etc. It is enough to be able to find such information if it is available.

2. `origin`: The purpose of this message is to determine information about the origin of the animal that can affect the characteristics of the animal, i.e. information such as strain, vendor, stock number, etc.

Here is an example:
```
subject:
  id: "DO021-1020" # Unique identifier for the laboratory mouse in MPD
  taxonomy:
    id: "NCBITaxon:10090"
    label: "Mus musculus"
  sex: "FEMALE"
  timeAtLastEncounter:
    ageRange:
      start:
          iso8601duration: "P4W" # 4 weeks
      end:
          iso8601duration: "P26W" # 26 weeks
  source:
    projectTitle: > # Title of the study or project
      Diet effects on Type 2 diabetes associated physiological traits
      in a Diversity Outbred (DO) mouse population on a high-fat high-sucrose diet
    database: "Mouse Phenome Database" # Database from which data was taken 
    projectIdentifier: "1020" # General project ID or database project ID
    subjectIdentifier: "DO021-1020" # Unique ID of this subject within the project or database
    releaseDate: "2020-10" # Release date of the project or subject
    publications: ["29567659"] # List of PubMed IDs
  origin:
    strain:
      id: "JAX:009376" # International Mouse Strain Resource (IMSR) identifier
      label: "j:DO"
      synonyms: ["Diversity Outbred", "DO"]
      phenotypicFeatures: # List of pheotypic traits associated with this strain (baseline)
      - type:
        id: "MP:0003012" # Mammalian phenotype ontology term
        label: "no phenotypic analysis"
    vendor: "Jackson Laboratory"
```
