### ISSUE TITLE
ESM element for treatments undefined

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/ExperimentalModelSchema#17]
In order to interpret a measurement correctly, it is crucial to know if any treatments were applied at the time of measurement, and if so, which treatments and over what period of time. Currently, treatments are insufficiently represented in the MPD schema (Issue #16) and an EMS element for treatments has not yet been defined.

The counterpart of an element for Treatments of mice would be [the `MedicalAction` element in the GA4GH Phenopacket schema](https://phenopacket-schema.readthedocs.io/en/latest/medical-action.html). Since the `MedicalAction` element is focused on modelling patients in a clinical context, it is only partially suitable for modelling experimental mouse data. I therefore propose to introduce a new element `Treatments` into the EMS. A message for a high-fat high sucrose diet applied from 4 to 26 weeks of life might look like this:

```
treatments:
- Diet:
   ageRange:
     start:
       iso8601duration: "P4W"
     end:
       iso8601duration: "P26W"
   type:
     id: "ONS:1000041" # Ontology for Nutritional Studies (ONS)
     label: "High fat diet" # No term for 'High fat high sucrose diet' in ONS
   schedule:
   - quantity:
       unit:
         id: "UO_0000021"
         label: "gram"
       value: 2.9072 # Average food intake per day
     frequency:
       id: "ONS:1000059"
       label: "Daily food intake"
   - composition:
       fat: 23.2
       carbohydrate: 47.6
       protein: 17.3
       kCalPerG: 4.7
```
For other types of `Treatments`, such as drug administration, other sub-elements could be introduced alongside `Diet`, such as `Agent`, where specific information such as the name of the agent and the route of administration could be documented.

I would like to point out that the data on treatments in MPD is represented in an unstructured form, which makes it impossible to automatically generate such messages as shown above (Issue #16). However, there is a wide range of well-documented treatments in the MPD, which may be helpful in modeling an adequate schema.
